// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  libcontainer

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( IO ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IO ) UnmarshalJSON([]byte) error { return nil }
func ( IO ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IO ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IO *IO

func ( Process ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Process ) UnmarshalJSON([]byte) error { return nil }
func ( Process ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Process ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Process *Process
